//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityPhone.DM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plan()
        {
            this.subscription = new HashSet<subscription>();
        }
    
        public int plan_id { get; set; }
        public string name { get; set; }
        public int minute_limit { get; set; }
        public int sms_limit { get; set; }
        public decimal price { get; set; }
        public decimal overage_minute_price { get; set; }
        public decimal overage_sms_price { get; set; }
        public bool is_available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscription> subscription { get; set; }
    }
}
